//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class appres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal appres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickServerDemo.appres", typeof(appres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;QuickServer Demo&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Hello and Welcome&lt;/h1&gt;
        ///		
        ///		&lt;p&gt;This is a simple http server written in C#. This implementation uses data hard coded into the server, or using resx files.&lt;/p&gt;
        ///		&lt;p&gt;Here is a list of places to visit:&lt;/p&gt;
        ///		&lt;ul&gt;
        ///			&lt;li&gt;&lt;a href=&quot;/splash&quot;&gt;A single image&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;/about&quot;&gt;about&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;/err&quot;&gt;a 500 server error test&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;/upload&quot;&gt;A simple image upload screen type thing (Pending i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rmfbsft0 {
            get {
                object obj = ResourceManager.GetObject("rmfbsft0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Hello! Fill out this form.&lt;/h1&gt;
        ///&lt;form action=&quot;/postimg&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot; style=&quot;display:flex; flex-direction:column&quot;&gt;
        ///    &lt;input type=&quot;text&quot; name=&quot;author&quot; /&gt;
        ///    &lt;input type=&quot;file&quot; name=&quot;image&quot; /&gt;
        ///    &lt;textarea name=&quot;description&quot;&gt;&lt;/textarea&gt;
        ///    &lt;input type=&quot;submit&quot; value=&quot;Post&quot; /&gt;
        ///&lt;/form&gt;.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
    }
}
